# Generated by Django 5.1.6 on 2025-03-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='AKyxaCUnRhLYBHUqjtoyDcjBBsjkK085', editable=False, max_length=32, unique=True),
        ),
    ]
