# Generated by Django 5.1.6 on 2025-03-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='gE8EKTKZLUcOXAW40WfMRrqmMC7qad1I', editable=False, max_length=32, unique=True),
        ),
    ]
